### ISSUE TITLE
expand fragment library

### ISSUE THREAD

**Issue by loriab** [psi4/libefp#1]
Psi4 has various S22 and S66 efp fragments from a Slipchenko repo that I can't find now. Can we get these in the libefp fragment library?

**Comment by loriab** [comment]
These are the extra fragments I've got.

```
#   fraglib/2aminopyridine.efp
#   fraglib/acetamide-gp.efp
#   fraglib/acetamide-hb.efp
#   fraglib/aceticacid-gp.efp
#   fraglib/aceticacid-hb.efp
#   fraglib/adenine-stack.efp
#   fraglib/adenine-wc.efp
#   fraglib/ammonia.efp
#   fraglib/benzene.efp
#   fraglib/cyclopentane.efp
#   fraglib/ethene.efp
#   fraglib/ethyne.efp
#   fraglib/formamide.efp
#   fraglib/formicacid.efp
#   fraglib/hydrogencyanide.efp
#   fraglib/indole.efp
#   fraglib/methane.efp
#   fraglib/methanol.efp
#   fraglib/methylamine.efp
#   fraglib/neopentane.efp
#   fraglib/nmethylacetamide.efp
#   fraglib/pentane.efp
#   fraglib/phenol.efp
#   fraglib/pyrazine.efp
#   fraglib/pyridine.efp
#   fraglib/pyridone.efp
#   fraglib/thymine-stack.efp
#   fraglib/thymine-wc.efp
#   fraglib/uracil-gp.efp
#   fraglib/uracil.efp
#   fraglib/water.efp
```

**Comment by ilyak** [comment]
As far as I remember there used to be a repo with some fragments from Slipchenko group. Is it gone now? I can put the frags you have into fraglib/extras or something like it.

**Comment by loriab** [comment]
It may still exist, I just couldn't find it. If the Slipchenko group isn't expanding theirs, it would be nice, in my view, to live in libefp. It would certainly be nice, from Psi4's view, to not be (1) shipping others' files, as we are now or (2) grabbing from multiple (yours and Slipchenko's) repos. If you're willing to do fraglib/extras in libefp, sounds great.

**Comment by ilyak** [comment]
https://github.com/makefp/EFP_potentials - seems like you have more/different set.

**Comment by loriab** [comment]
After some `diff`ing, I conclude psi4 has the same set as EFP_potentials/gamess, just with different names. (I do like the psi4 names better, but I can comprimise.)

Since you're distributing gamess fragments anyway, I think it'd be nice to add these to the libefp library, either `fraglib` or `fraglib/extras`. Identification with S22 or S66 can go in the subdirectory README.md. If you're agreeable to the plan @ilyak, @CDSherrill can confer with Slipchenko at ACS.

```
#   2aminopyridine.efp  s22/AMINOP.efp
#   acetamide-gp.efp    s66/ACNH2G.efp
#   acetamide-hb.efp    s66/ACNH2B.efp
#   aceticacid-gp.efp   s66/ACOHG.efp
#   aceticacid-hb.efp   s66/ACOHB.efp   
#   adenine-stack.efp   s22/ADENIN.efp
#   adenine-wc.efp      s22/ADENI2.efp
#   ammonia.efp         s22/AMONIA.efp
#   benzene.efp         s22/BENZEN.efp
#   cyclopentane.efp    s66/CYCPEN.efp
#   ethene.efp          s22/ETHENE.efp
#   ethyne.efp          s22/ETHYNE.efp
#   formamide.efp       s22/FORMID.efp
#   formicacid.efp      s22/FORMIC.efp
#   hydrogencyanide.efp s22/HCN.efp 
#   indole.efp          s22/INDOLE.efp
#   methane.efp         s22/METHAN.efp
#   methanol.efp        s66/MEOH.efp
#   methylamine.efp     s66/MENH2.efp 
#   neopentane.efp      s66/NEOPEN.efp
#   nmethylacetamide.efp    s66/PEPTID.efp
#   pentane.efp         s66/PENTAN.efp
#   phenol.efp          s22/PHENOL.efp
#   pyrazine.efp        s22/PYRAZI.efp
#   pyridine.efp        s66/PYRIDI.efp
#   pyridone.efp        s22/PYRIDO.efp
#   thymine-stack.efp   s22/THYMIN.efp
#   thymine-wc.efp      s22/THYMI2.efp
#   uracil-gp.efp       s66/URACG.efp
#   uracil.efp          s22/URACIL.efp
#   water.efp           s22/WATER.efp
```
